import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getTestCases } from '../api';
import StatusBadge from '../components/StatusBadge';

export default function TestCases() {
  const [data, setData] = useState(null);
  const [page, setPage] = useState(1);
  const [project, setProject] = useState('');
  const [suite, setSuite] = useState('');
  const [source, setSource] = useState('');
  const [priority, setPriority] = useState('');
  const [status, setStatus] = useState('');

  useEffect(() => {
    setPage(1);
  }, [project, suite, source, priority, status]);

  useEffect(() => {
    getTestCases({
      page,
      limit: 15,
      project: project || undefined,
      suite: suite || undefined,
      source: source || undefined,
      priority: priority || undefined,
      status: status || undefined
    }).then(setData);
  }, [page, project, suite, source, priority, status]);

  const totalPages = data ? Math.ceil(data.total / data.limit) : 1;

  return (
    <div>
      <div className="section-title">Test Cases</div>
      <div className="muted" style={{ marginTop: -6, marginBottom: 16 }}>
        Test case definitions created manually or generated by an AI assistant through the MCP server.
      </div>

      <div className="filter-bar">
        <input placeholder="Project" value={project} onChange={(e) => setProject(e.target.value)} />
        <input placeholder="Suite" value={suite} onChange={(e) => setSuite(e.target.value)} />
        <select value={source} onChange={(e) => setSource(e.target.value)}>
          <option value="">All sources</option>
          <option value="ai-generated">AI-generated (MCP)</option>
          <option value="manual">Manual</option>
        </select>
        <select value={priority} onChange={(e) => setPriority(e.target.value)}>
          <option value="">All priorities</option>
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
          <option value="critical">Critical</option>
        </select>
        <select value={status} onChange={(e) => setStatus(e.target.value)}>
          <option value="">All statuses</option>
          <option value="draft">Draft</option>
          <option value="active">Active</option>
          <option value="deprecated">Deprecated</option>
        </select>
      </div>

      <div className="card" style={{ padding: 0 }}>
        {data?.testCases?.length ? (
          <table>
            <thead>
              <tr>
                <th>Title</th>
                <th>Project / Suite</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Source</th>
                <th>Tags</th>
                <th>Created</th>
              </tr>
            </thead>
            <tbody>
              {data.testCases.map((tc) => (
                <tr key={tc._id}>
                  <td>
                    <Link to={`/testcases/${tc._id}`}>{tc.title}</Link>
                  </td>
                  <td className="muted">
                    {tc.project} / {tc.suite}
                  </td>
                  <td>
                    <StatusBadge status={tc.priority} />
                  </td>
                  <td>
                    <StatusBadge status={tc.status} />
                  </td>
                  <td>
                    <StatusBadge status={tc.source} />
                  </td>
                  <td className="muted">{tc.tags?.join(', ') || '—'}</td>
                  <td className="muted">{new Date(tc.createdAt).toLocaleDateString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <div className="empty-state">No test cases yet.</div>
        )}
      </div>

      {totalPages > 1 && (
        <div style={{ display: 'flex', gap: 10, marginTop: 12, fontSize: 13 }}>
          <button disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>
            Previous
          </button>
          <span className="muted">
            Page {page} of {totalPages}
          </span>
          <button disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}>
            Next
          </button>
        </div>
      )}
    </div>
  );
}
